import store from '@/Redux Store/store'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import '@/styles/globals.css'
import Head from 'next/head'
import { Provider } from 'react-redux'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Full Stack Shoe Website for Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Provider store={store}>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </Provider>
    </>
  )
}
